---
- name: apply the common conf to all hosts
  hosts: all
  become: yes

  roles:
  - common

- name: Deploy MS to machines
  hosts: ms
  become: yes

  roles:
  - ms

- name: Deploy AAA to machines
  hosts: aaa
  become: yes

  roles:
  - aaa

- name: Generate Conf and Execute Servers
  hosts: aaaservers
  become: yes

  roles:
  - server 
  
- name: Generate Conf and Execute Proxies
  hosts: aaaproxies
  become: yes

  roles:
  - proxy

