
- hosts: Servers
  name: Deployment
  gather_facts: no
  remote_user: root
  #strategy: debug

  tasks:

# Backup old files

    - name: copy previous version
      command: cp -R /var/run/AAA/AAAServer/conf /var/run/AAA/conf
      ignore_errors: yes
      register: isExist

# Reload Actual Conf files
    - block:
       - name: copy actual conf files
         command: cp -R /var/run/AAA/conf /var/run/AAA/AAAServer/

       - name: remove backup file
         file: path=/var/run/AAA/conf state=absent
      when: isExist|succeeded

