
- hosts: aaaservers
  name: Deployment
  gather_facts: no
  remote_user: root
  #strategy: debug

  tasks:

# Check if AAA is running

#    - name: Check opened ports by AAA
#      shell: netstat -peanut | grep drs | grep 3868
#      ignore_errors: yes
#      register: isExist

#    - name: print aaa process ids 
#      debug: msg="{{ isExist.stdout_lines }}"

