---
# Upload test db to server
#- block:
#   - name: Upload test db to remote server
#     copy: src={{ playbook_dir }}/roles/ms/files/aaa_orm.mv.db dest={{ ansible_env.HOME }}
#     when: ansible_host !="10.45.0.9"

#   - name: Upload test db to remote server
#     copy: src={{ playbook_dir }}/roles/ms/files/staging/aaa_orm.mv.db dest={{ ansible_env.HOME }}
#     when: ansible_host =="10.45.0.9"
#  when: freshConf == true

- block:
   #- name: wait for me to tailf log file
   #  pause: seconds=30

   - name: wait for 8080 port to be started
     wait_for:
       host: "{{ ansible_host }}"
       port: 8080
       state: started

   #- name: Pause 60 seconds
   #  pause: seconds=60

   - name: Login to MS
     uri:
       url: http://{{ ansible_host }}:8080/login?username=demo&password=demo
       method: POST
       #force_basic_auth: yes
       #user: demo
       #password: demo
       #body: "username=demo&password=demo"
       status_code: 302
       headers:
         Content-Type: "application/json"
     register: login

   - debug: msg={{ login }} 

   - name: Send AddInstance Request to MS
     uri:
       url: http://{{ ansible_host }}:8080/api/instances
       method: POST
       force_basic_auth: yes
       status_code: 200
       body_format: json
       body: "{{ lookup('file','{{ item }}') }}"
       headers:
         Content-Type: "application/json"
         Cookie: "{{login.set_cookie}}"
     with_fileglob:
       - "roles/ms/files/*.json"
  when: freshConf == true
