---
# Delete existing required folders to prevent any errors

#- file: path={{ temp_dir }} state=absent
#  tags:
#     - reset
#- file: path={{ ms_directory }} state=absent
#  tags:
#     - reset
- file: path={{ db_backup_dir }} state=absent
  tags:
     - reset

# Backup db

- name: create db backup directory
  file: path={{ db_backup_dir }} state=directory

- name: backup previous load conf files
  command: cp {{ ms_directory }}/aaa_orm.mv.db {{ db_backup_dir }}
  ignore_errors: yes
  register: isExist

- set_fact: freshConf=true

# Management Server bundle upload operations 

- name: create temp directory
  file: path={{ temp_dir }} state=directory

- name: retrieve bundle list from directory
  local_action: find paths="{{ playbook_dir }}/roles/aaa/files" patterns="MS_*.tar.gz"
  register: bundle

- name: upload bundle
  copy: src={{ bundle.files.0.path }} dest={{ temp_dir }}

#- name: copy bundle to {{ temp_dir }} it is a temp task to prevent upload file from home
#  command: cp -fu /tmp/{{ bundle.files.0.path | basename }} {{ temp_dir }}

- name: create ms directory
  file: path={{ ms_directory }} state=directory

- name: unarchive bundle file
  unarchive: src={{ temp_dir }}/{{ bundle.files.0.path | basename }} dest={{ ms_directory }} remote_src=True

- name: delete temp directory
  file: path={{ temp_dir }} state=absent


# Recover backup db data

- block:
    - name: recover backup db data
      command: cp -a {{ db_backup_dir }}/. {{ ms_directory }}

    - name: remove backup file
      file: path={{ db_backup_dir }} state=absent

    - set_fact: freshConf=false
  when: isExist|succeeded

- file: path={{ db_backup_dir }} state=absent  

#- debug: var=freshConf

- include: executor.yml

